export const OPEN_CREATE_TODO_MODAL = 'openWindowCreateToDo';
export const CLOSE_MODAL_CREATE_TODO = 'closeModalCreateToDo';
export const CREATE_TODO = 'createToDoItem';
export const ADD_LIST_PRIORITY_TODO = 'addListPriorityToDoItem';
export const IS_CHECKED_PUT_POST = 'checkedPutPost';
export const UPDATE_SELECTED = 'updateSelectedItem';
export const SET_TODO_LIST = 'setTodoList';
export const EDIT_SELECTED_TODO = 'editSelectedTodo';
export const UPDATE_LIST_TODO = 'updateToDoList ';
